# Generated by Django 3.1 on 2020-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200827_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_count',
            field=models.IntegerField(default=25),
        ),
    ]
