# Generated by Django 3.1 on 2020-08-27 13:22

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_max_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
