# Generated by Django 3.1 on 2020-08-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_name'),
        ('course', '0004_auto_20200829_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='student.Student'),
        ),
    ]
