# Generated by Django 3.1 on 2020-08-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200827_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
