# Generated by Django 3.1 on 2020-08-28 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 2, 22, 9, 821490)),
        ),
    ]
