# Generated by Django 3.1 on 2020-08-28 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 2, 31, 57, 896335)),
        ),
    ]
