# Generated by Django 3.1 on 2020-08-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courseattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='teachers/default.jpg', upload_to='teachers/'),
        ),
    ]
