# Generated by Django 3.1 on 2020-08-28 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200828_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 2, 35, 21, 19270)),
        ),
    ]
