# Generated by Django 3.1 on 2020-08-31 03:43

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='achievements',
            field=djrichtextfield.models.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2001, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(default='Нюрба', max_length=63),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='languages_list',
            field=models.CharField(default='Якутский язык; Русский язык;', max_length=100),
        ),
    ]
