# Generated by Django 3.1 on 2020-08-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200828_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
