# Generated by Django 3.1 on 2020-08-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200831_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='achievements',
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
