# Generated by Django 3.1 on 2020-08-29 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CE', 'Детское образовательное учреждение'), ('SE', 'Образовательное учреждение'), ('AE', 'Дополнительное образование')], max_length=2)),
                ('image', models.ImageField(upload_to='school/')),
                ('name', models.CharField(max_length=255)),
                ('description', djrichtextfield.models.RichTextField()),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=11)),
                ('child_amount', models.IntegerField(default=0)),
                ('min_grade', models.IntegerField(default=5)),
                ('max_grade', models.IntegerField(default=11)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.CharField(blank=True, max_length=63)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='adverts/default.jpg', upload_to='adverts/')),
                ('title', models.CharField(max_length=127)),
                ('content', djrichtextfield.models.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
