# Generated by Django 3.1 on 2020-08-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
    ]
