# Generated by Django 3.1 on 2020-08-27 13:22

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
