# Generated by Django 3.1 on 2020-08-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200827_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(default='media/school/ntl.jpg', upload_to='media/school/'),
        ),
    ]
