# Generated by Django 3.1 on 2020-08-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_school_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(default='school/ntl.jpg', upload_to='school/'),
        ),
    ]
