# Generated by Django 3.1 on 2020-08-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200828_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(upload_to='school/'),
        ),
    ]
