# Generated by Django 3.1 on 2020-08-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200828_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('CE', 'Дошкольное образовательное учреждение'), ('ME', 'Образовательное учреждение'), ('UE', 'Дополнительное образование')], default='ME', max_length=2),
            preserve_default=False,
        ),
    ]
