# Generated by Django 3.1 on 2020-08-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='site',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('CE', 'Детское образовательное учреждение'), ('ME', 'Образовательное учреждение'), ('UE', 'Дополнительное образование')], max_length=2),
        ),
    ]
