# Generated by Django 3.1 on 2020-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200828_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='child_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('CE', 'Детское образовательное учреждение'), ('SE', 'Образовательное учреждение'), ('AE', 'Дополнительное образование')], max_length=2),
        ),
    ]
