# Generated by Django 3.1 on 2020-08-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20200828_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_grade',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='school',
            name='min_grade',
            field=models.IntegerField(default=5),
        ),
    ]
