# Generated by Django 3.1 on 2020-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200828_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='adverts/default.jpg', upload_to='adverts/'),
        ),
    ]
