# Generated by Django 3.1 on 2020-08-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('SH', 'Образовательная организация'), ('TH', 'Учитель'), ('PR', 'Ученик')], max_length=2),
        ),
    ]
