# Generated by Django 3.1 on 2020-08-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
